--- #YAML:1.0
name:               Crypt-URandom
version:            0.28
abstract:           Provide non blocking randomness
author:
    - David Dick <ddick@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:        0
    English:     0
    FileHandle:  0
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
